# Generated by Django 2.2.1 on 2019-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productdetails',
            field=models.CharField(max_length=500),
        ),
    ]
