# Generated by Django 2.2.1 on 2019-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190807_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productdetails',
            field=models.CharField(max_length=1000),
        ),
    ]
